name: Node.js CI/CD

on:
  push:
    branches:
      - main # Trigger on push to the 'main' branch
  pull_request:
    branches:
      - main # Trigger on pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout the repository
    - name: Checkout repository
      uses: actions/checkout@v3

    # Setup Node.js
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16' # Set your required Node.js version

    # Install dependencies
    - name: Install dependencies
      run: npm install

    # Run tests (optional: if you have tests in your project)
    - name: Run tests
      run: npm test

    # Build the application (if applicable)
    - name: Build project
      run: npm run build # Skip if not using a build step

    # Deploy application (optional)
    # - name: Deploy to Heroku or Render
    #   if: github.event_name == 'push'
    #   run: |
    #     echo "Deployment steps go here" # Replace this with actual deployment steps
